---
training_stages:
  
  - id: 0
    resize: 146
    res: 128
    centered: False
    RandAugment_magnitude: 5
    dropout_prob: 0.1
    lr_min: 0.00000064
    lr_max: 0.00064
    decay_mode: exp
    decay_factor: 0.9873
    warmup_epochs: 20
    epochs: 70
    cutmix_alpha: 0.0
    mixup_alpha: 0.0
    label_smoothing: 0.0
