---
training_stages:
  
  - id: 0
    resize: 186
    res: 164
    centered: False
    RandAugment_magnitude: 10
    dropout_prob: 0.1
    lr_min: 0.00005
    lr_max: 0.00015
    decay_mode: exp
    decay_factor: 0.97
    warmup_epochs: 5
    epochs: 80
