---
training_stages:
  
  - id: 0
    resize: 124
    res: 124
    centered: False
    RandAugment_magnitude: 5
    dropout_prob: 0.1
    lr_min: 0.00008
    lr_max: 0.0008
    decay_mode: exp
    decay_factor: 0.975
    warmup_epochs: 25
    epochs: 70
    cutmix_alpha: 0.0
    mixup_alpha: 0.0
    label_smoothing: 0.0

  - id: 1
    resize: 168
    res: 168
    centered: False
    RandAugment_magnitude: 8
    dropout_prob: 0.15
    lr_min: 0.00004
    lr_max: 0.0004
    decay_mode: exp
    decay_factor: 0.98
    warmup_epochs: 25
    epochs: 70
    cutmix_alpha: 0.0
    mixup_alpha: 0.0
    label_smoothing: 0.0

  - id: 2
    resize: 184
    res: 184
    centered: False
    RandAugment_magnitude: 12
    dropout_prob: 0.2
    lr_min: 0.00002
    lr_max: 0.0002
    decay_mode: exp
    decay_factor: 0.98
    warmup_epochs: 25
    epochs: 70
    cutmix_alpha: 0.0
    mixup_alpha: 0.0
    label_smoothing: 0.0

  - id: 3
    resize: 256
    res: 224
    centered: True
    RandAugment_magnitude: 15
    dropout_prob: 0.25
    lr_min: 0.00001
    lr_max: 0.0001
    decay_mode: exp
    decay_factor: 0.98
    warmup_epochs: 25
    epochs: 70
    cutmix_alpha: 1.0
    mixup_alpha: 0.1
    label_smoothing: 0.0
