---
training_stages:
  
  - id: 0
    resize: 146
    res: 124
    centered: False
    RandAugment_magnitude: 5
    dropout_prob: 0.1
    lr_min: 0.00005
    lr_max: 0.0005
    decay_mode: exp
    decay_factor: 0.9845
    warmup_epochs: 15
    epochs: 100
    cutmix_alpha: 1
    mixup_alpha: 0.1
