---
training_stages:
  
  - id: 0
    resize: 146
    res: 128
    centered: False
    RandAugment_magnitude: 5
    dropout_prob: 0.1
    lr_min: 0.00000064
    lr_max: 0.00064
    decay_mode: exp
    decay_factor: 0.9873
    warmup_epochs: 20
    epochs: 70
    cutmix_alpha: 0.0
    mixup_alpha: 0.0
    label_smoothing: 0.0

  - id: 1
    resize: 184
    res: 168
    centered: False
    RandAugment_magnitude: 8
    dropout_prob: 0.15
    lr_min: 0.00000000002
    lr_max: 0.000112593
    decay_mode: exp
    decay_factor: 0.988
    warmup_epochs: 0
    epochs: 70
    cutmix_alpha: 0.0
    mixup_alpha: 0.0
    label_smoothing: 0.0

  - id: 2
    resize: 218
    res: 184
    centered: False
    RandAugment_magnitude: 12
    dropout_prob: 0.2
    lr_min: 0.00000000002
    lr_max: 0.00004836
    decay_mode: exp
    decay_factor: 0.9885
    warmup_epochs: 0
    epochs: 70
    cutmix_alpha: 0.0
    mixup_alpha: 0.0
    label_smoothing: 0.0

  - id: 3
    resize: 256
    res: 224
    centered: True
    RandAugment_magnitude: 15
    dropout_prob: 0.25
    lr_min: 0.00000000001
    lr_max: 0.000021520999035025463
    decay_mode: exp
    decay_factor: 0.9885
    warmup_epochs: 0
    epochs: 70
    cutmix_alpha: 1.0
    mixup_alpha: 0.1
    label_smoothing: 0.0
