---
training_stages:
  
  - id: 0
    resize: 146
    res: 124
    centered: False
    RandAugment_magnitude: 5
    dropout_prob: 0.1
    lr_min: 0.000025
    lr_max: 0.0025
    decay_mode: exp
    decay_factor: 0.975
    warmup_epochs: 25
    epochs: 70
    cutmix_alpha: 0.0
    mixup_alpha: 0.0
    label_smoothing: 0.0

  - id: 1
    resize: 184
    res: 168
    centered: False
    RandAugment_magnitude: 8
    dropout_prob: 0.15
    lr_min: 0.000125
    lr_max: 0.00125
    decay_mode: exp
    decay_factor: 0.975
    warmup_epochs: 25
    epochs: 70
    cutmix_alpha: 0.0
    mixup_alpha: 0.0
    label_smoothing: 0.0

  - id: 2
    resize: 224
    res: 184
    centered: False
    RandAugment_magnitude: 12
    dropout_prob: 0.2
    lr_min: 0.000075
    lr_max: 0.00075
    decay_mode: exp
    decay_factor: 0.975
    warmup_epochs: 25
    epochs: 70
    cutmix_alpha: 0.0
    mixup_alpha: 0.0
    label_smoothing: 0.0

  - id: 3
    resize: 256
    res: 224
    centered: True
    RandAugment_magnitude: 15
    dropout_prob: 0.25
    lr_min: 0.0000375
    lr_max: 0.000375
    decay_mode: exp
    decay_factor: 0.975
    warmup_epochs: 25
    epochs: 70
    cutmix_alpha: 1.0
    mixup_alpha: 0.1
    label_smoothing: 0.1
