---
training_stages:
  
  - id: 0
    resize: 164
    res: 124
    centered: False
    RandAugment_magnitude: 5
    dropout_prob: 0.1
    lr_min: 0.00005
    lr_max: 0.00095
    decay_mode: exp
    decay_factor: 0.986
    warmup_epochs: 15
    epochs: 100
