---
settings:

  - id: 0
    train_dir: ~/.cache/kagglehub/datasets/ethanelkayam/dataset1/versions/1/newdata3
    test_dir: ~/.cache/kagglehub/datasets/ethanelkayam/dataset2/versions/1/nntestingdata
    batch_size: 256
    dataloader_num_workers: 24
    dataset_num_workers: 24
    momentum: 0.9
    weight_decay: 0.00001
    lazy_dataset: True
    half_precision: True
    train_split: 100
    max_class_size: 1300
    min_class_size: 800
    mean: [0.4665552622511037, 0.4587000404130766, 0.4476851038301765]
    std: [0.2561551292582817, 0.2449296727629446, 0.2647244509669918]
