---
training_general:

  - id: 0
    batch_size: 256
    dataloader_num_workers: 14
    dataset_num_workers: 32
    momentum: 0.8
    weight_decay: 0.00005
    lazy_dataset: True
    ds_mean: [0.485, 0.456, 0.406]
    ds_std: [0.229, 0.224, 0.225]
