---
training_general:

  - id: 0
    batch_size: 512
    dataloader_num_workers: 20
    dataset_num_workers: 48
    momentum: 0.8
    weight_decay: 0.00001
    lazy_dataset: False
    ds_mean: [0.4925, 0.4561, 0.4017]
    ds_std: [0.2909, 0.2837, 0.2993]
