---
training_general:

  - id: 0
    batch_size: 1024
    dataloader_num_workers: 24
    dataset_num_workers: 24
    momentum: 0.9
    weight_decay: 0.00001
    lazy_dataset: True
    half_precision: True
    ds_mean: [0.485, 0.456, 0.406]
    ds_std: [0.229, 0.224, 0.225]
